name: Test and Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for OIDC
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Update npm for OIDC trusted publishing
        run: npm install -g npm@latest

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"

      - name: Gitversion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Build and test
        run: |
          pnpm install
          pnpm build
          pnpm typecheck
          pnpm test

      - name: Set Version
        run: pnpm -F './packages/**/*' exec json -f "package.json" -I -e 'this.version = "${{ steps.gitversion.outputs.fullSemVer }}"'

      - name: Publish @drawcall/rig
        working-directory: ./packages/rig
        run: pnpm publish --access public --no-git-checks --tag latest
